CREATE DATABASE DB_CRUD;

DROP TABLE tb_estados;
CREATE TABLE tb_estados(
EST_ID INT NOT NULL AUTO_INCREMENT,
EST_NOME CHAR(2),

CONSTRAINT PK_tb_estados PRIMARY KEY (EST_ID)
);

DROP TABLE tb_cidades;
CREATE TABLE tb_cidades(
CID_ID INT NOT NULL AUTO_INCREMENT,
CID_NOME VARCHAR(50),
CID_EST_ID INT,

CONSTRAINT PK_tb_cidades PRIMARY KEY (CID_ID),
CONSTRAINT FK_EST_CID FOREIGN KEY (CID_EST_ID)
REFERENCES tb_estados (EST_ID)
);

DROP TABLE tb_bairros;
CREATE TABLE tb_bairros(
BAI_ID INT NOT NULL AUTO_INCREMENT,
BAI_NOME VARCHAR(50),
BAI_CID_ID INT,

CONSTRAINT PK_tb_bairros PRIMARY KEY (BAI_ID),
CONSTRAINT FK_CID_BAI FOREIGN KEY (BAI_CID_ID)
REFERENCES tb_cidades (CID_ID)
);

CREATE TABLE tb_clientes(
CLI_ID INT NOT NULL AUTO_INCREMENT,
CLI_NOME VARCHAR(100),
CLI_EMAIL VARCHAR(100),
CLI_LOGRADOURO VARCHAR(255),
CLI_NUMERO INT,
CLI_COMPLEMENTO VARCHAR(255),
CLI_CEP CHAR(7),
CLI_BAI_ID INT,
CLI_CID_ID INT,
CLI_EST_ID INT,

CONSTRAINT PK_tb_clientes PRIMARY KEY (CLI_ID),

CONSTRAINT FK_BAI_CLI FOREIGN KEY (CLI_BAI_ID)
REFERENCES tb_bairros(BAI_ID),
CONSTRAINT FK_CID_CLI FOREIGN KEY (CLI_CID_ID)
REFERENCES tb_cidades(CID_ID),
CONSTRAINT FK_EST_CLI FOREIGN KEY (CLI_EST_ID)
REFERENCES tb_estados(EST_ID)
);

-- CREATE TABLE tb_clientes(
-- CLI_CODIGO INT NOT NULL AUTO_INCREMENT,
-- CLI_NOME VARCHAR(100),
-- CLI_EMAIL VARCHAR(100),
-- CLI_LOGRADOURO VARCHAR(255),
-- CLI_NUMERO INT,
-- CLI_COMPLEMENTO VARCHAR(255),
-- CLI_CEP CHAR(7),
-- CLI_BAI_CODIGO INT,
-- CLI_CID_CODIGO INT,
-- CLI_EST_CODIGO INT,
-- CONSTRAINT PK_tb_clientes PRIMARY KEY (CLI_CODIGO),
-- CONSTRAINT FK_BAI_CLI FOREIGN KEY (CLI_BAI_CODIGO)
-- REFERENCES tb_bairros(BAI_CODIGO),
-- CONSTRAINT FK_CID_CLI FOREIGN KEY (CLI_CID_CODIGO)
-- REFERENCES tb_cidades(CID_CODIGO),
-- CONSTRAINT FK_EST_CLI FOREIGN KEY (CLI_EST_CODIGO)
-- REFERENCES tb_estados(EST_CODIGO)
-- );

CREATE TABLE tb_setores(
SET_ID INT NOT NULL AUTO_INCREMENT,
SET_NOME VARCHAR(50),
CONSTRAINT PK_tb_setores PRIMARY KEY (SET_ID)
);

CREATE TABLE tb_funcoes(
FUN_ID INT NOT NULL AUTO_INCREMENT,
FUN_NOME VARCHAR(50),
FUN_SET_ID INT,
CONSTRAINT PK_tb_funcoes PRIMARY KEY (FUN_ID),
CONSTRAINT FK_SET_FUN FOREIGN KEY (FUN_SET_ID)
REFERENCES tb_setores(SET_ID)
);

DROP TABLE tb_employers;
CREATE TABLE tb_employers(
EMP_ID INT NOT NULL AUTO_INCREMENT,
EMP_NOME VARCHAR(100),
EMP_STATUS VARCHAR(100),
EMP_IDENTIDADE VARCHAR(15),
EMP_CPF CHAR(15),
EMP_CAR_TRAB VARCHAR(15),
EMP_DATA_NASCIMENTO DATE,
EMP_DATA_ADMISSAO DATE,
EMP_DATA_REGISTRO DATE,
EMP_SEXO CHAR(1),
EMP_ESTADO_CIVIL VARCHAR(15),
EMP_FILHOS INT,
EMP_EMAIL VARCHAR(100),
EMP_LOGRADOURO VARCHAR(255),
EMP_NUMERO VARCHAR(10),
EMP_COMPLEMENTO VARCHAR(255),
EMP_CEP CHAR(9),
EMP_FUN_ID INT,
EMP_SET_ID INT,
EMP_BAI_ID INT,
EMP_CID_ID INT,
EMP_EST_ID INT,

CONSTRAINT PK_tb_servidores PRIMARY KEY (EMP_ID),
CONSTRAINT FK_BAI_EMP FOREIGN KEY (EMP_BAI_ID)
REFERENCES tb_bairros(BAI_ID),
CONSTRAINT FK_CID_EMP FOREIGN KEY (EMP_CID_ID)
REFERENCES tb_cidades(CID_ID),
CONSTRAINT FK_EST_EMP FOREIGN KEY (EMP_EST_ID)
REFERENCES tb_estados(EST_ID),
CONSTRAINT FK_FUN_EMP FOREIGN KEY (EMP_FUN_ID)
REFERENCES tb_funcoes(FUN_ID),
CONSTRAINT FK_SET_EMP FOREIGN KEY (EMP_SET_ID)
REFERENCES tb_setores(SET_ID)
);

-- INSERTS
DROP TABLE tb_estados;
INSERT INTO tb_estados(EST_NOME) VALUES('PB');
INSERT INTO tb_estados(EST_NOME) VALUES('RN');
INSERT INTO tb_estados(EST_NOME) VALUES('RJ');
INSERT INTO tb_estados(EST_NOME) VALUES('AC');
INSERT INTO tb_estados(EST_NOME) VALUES('MA');
INSERT INTO tb_estados(EST_NOME) VALUES('SE');
DELETE FROM tb_estados WHERE EST_CODIGO = 1;

INSERT INTO tb_cidades(CID_NOME,CID_EST_CODIGO) VALUES('PARELHAS',1);
DELETE FROM tb_cidades WHERE CID_CODIGO = 4;